title: OpenVINO by Intel CVPR-2022
logo: https://user-images.githubusercontent.com/10940214/165390101-564547d2-6828-45b7-abb2-01ff556772e2.png
description: How to get quick and performant model for your edge application. From data to application.
#authors:
#  social:
#    email:    mailto:paula.ramos@intel.com
#    linkedin: https://www.linkedin.com/in/paula-ramos-41097319/
#  picture:
#    path:   /img/paula.jpg
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
